from django.contrib import admin
from .models import *


admin.site.register(Info)
admin.site.register(MainBanner)
admin.site.register(Region)
admin.site.register(Residence)
admin.site.register(Flat)
admin.site.register(RoomQuantity)
admin.site.register(ResidenceImage)
admin.site.register(ResidenceClass)
admin.site.register(Finishing)
admin.site.register(PaymentBanner)
admin.site.register(PaymentType)
admin.site.register(PercentageBanner)
admin.site.register(Developer)
admin.site.register(DeveloperImage)
admin.site.register(Appointment)
admin.site.register(AppointmentBanner)
admin.site.register(HouseType)
admin.site.register(BalconyType)
admin.site.register(HeatingSystem)
admin.site.register(Territory)
admin.site.register(ResidenceFeature)
admin.site.register(PlacesNearby)
admin.site.register(ParkingType)
admin.site.register(RealtorBanner)
admin.site.register(FindRealtor)
admin.site.register(RealtorBenefit)
admin.site.register(Realtor)
admin.site.register(HowItWork)