# Generated by Django 4.1.6 on 2023-11-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_region_residence_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='room_quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.roomquantity'),
            preserve_default=False,
        ),
    ]
