# Generated by Django 4.1.6 on 2023-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomquantity_flat_room_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomquantity',
            name='quantity',
            field=models.CharField(max_length=250),
        ),
    ]
