# Generated by Django 4.1.6 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_roomquantity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
