# Generated by Django 4.1.6 on 2023-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_flat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
