# Generated by Django 4.1.6 on 2023-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_flat_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='lang',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='long',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
