# Generated by Django 4.1.6 on 2023-11-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_residence_residence_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='residence_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.residenceclass'),
            preserve_default=False,
        ),
    ]
