# Generated by Django 4.1.6 on 2023-11-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_residence_residence_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='price_for_a_meter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
