# Generated by Django 4.1.6 on 2023-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_residence_price_for_a_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
