# Generated by Django 4.1.6 on 2023-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_residence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
