# Generated by Django 4.1.6 on 2023-11-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_residence_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='floors_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='install_payment',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='price',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='finishing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.finishing'),
            preserve_default=False,
        ),
    ]
