# Generated by Django 4.1.6 on 2023-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_finishing_residence_floors_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
