# Generated by Django 4.1.6 on 2023-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('percent', models.IntegerField()),
                ('percentage_name', models.CharField(max_length=250)),
            ],
        ),
    ]
