# Generated by Django 4.1.6 on 2023-11-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_developerimage_developer_residence_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.developer'),
        ),
    ]
