# Generated by Django 4.1.6 on 2023-11-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='banners/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
