# Generated by Django 4.1.6 on 2023-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_appointmentbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fb',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='insta',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='tg',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='yt',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
