# Generated by Django 4.1.6 on 2023-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_realtorbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('review_quantity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='realtors/')),
            ],
        ),
    ]
