# Generated by Django 4.1.6 on 2023-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_howitwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residences/')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='images',
            field=models.ImageField(default=1, upload_to='residences/'),
            preserve_default=False,
        ),
    ]
